#include "jdarcade.h"
#include "jdprotocol.h"
#include <string.h>
#include <stdio.h>

#define DEVICE_NAME "Arcade ProtoShield v1.0"
#define NUM_PLAYERS 1

#define DISPLAY_FLAGS 0
#define BUTTON_FLAGS 0

void jd_add_ad_data(const char *name, uint32_t class, uint8_t flags, const void *src,
                    uint32_t size);

static const jd_display_advertisement_data_t displayAd = {
    .flags = JD_DISPLAY_FLAGS_RETINA, .bpp = 4, .width = 160, .height = 120};

static uint16_t buttonAd[] = { //
    BUTTON_FLAGS | (NUM_PLAYERS << 8), JD_ARCADE_CONTROLS_BUTTON_LEFT, JD_ARCADE_CONTROLS_BUTTON_UP,
    JD_ARCADE_CONTROLS_BUTTON_RIGHT,   JD_ARCADE_CONTROLS_BUTTON_DOWN, JD_ARCADE_CONTROLS_BUTTON_A,
    JD_ARCADE_CONTROLS_BUTTON_B,       JD_ARCADE_CONTROLS_BUTTON_MENU};

void jd_add_services() {
    jd_add_ad_data("Display 160x128x4bpp", JD_SERVICE_CLASS_DISPLAY, 0, &displayAd,
                   sizeof(displayAd));
    jd_add_ad_data("Arcade controls", JD_SERVICE_CLASS_ARCADE_CONTROLS, 0, &buttonAd,
                   sizeof(buttonAd));
}

void print_bytes(const void *src, uint32_t size) {
    for (int i = 0; i < size; ++i) {
        printf(" 0x%02x,", ((uint8_t *)src)[i]);
        if (i % 16 == 15)
            printf("\n");
    }
}

void jd_add_ad_data(const char *name, uint32_t class, uint8_t flags, const void *src,
                    uint32_t size) {
    printf("// Service %s (class=0x%08x, flags=0x%02x)\n", name, class, flags);
    print_bytes(&class, 4);
    print_bytes(&flags, 1);
    print_bytes(&size, 1);
    print_bytes(src, size);
    printf("\n");
}

void jd_fill_ad_data() {
    printf("// Device name: \"%s\"\n", DEVICE_NAME);
    uint8_t flags = JD_DEVICE_FLAGS_HAS_NAME;
    print_bytes(&flags, 1);
    int len = strlen(DEVICE_NAME);
    print_bytes(&len, 1);
    print_bytes(DEVICE_NAME, len);
    printf("\n");
    jd_add_services();
}

int main() {
    printf("// Generated by genad.c\n");
    printf("const static uint8_t adData[] = {\n");
    jd_fill_ad_data();
    printf("};\n");
    printf("// End of generated code\n");
    return 0;
}
